<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<!-- Styles -->
<link href="css/style.css" rel="stylesheet">
<?php
echo $this->Html->script('bootstrap.min') . "\n";
echo $this->Html->script('menu') . "\n";
echo $this->fetch('script');

echo $this->Html->css('bootstrap.min') . "\n";
echo $this->Html->css('style') . "\n";
echo $this->fetch('css');
?>

<div class="container">
    <header class="row">
        <h4>Escola ABC123</h4>

    </header>
    <div class="row" >
        <aside role="complementary" class="col-md-4" >


            <div class='span3' >
                <ul class="nav nav-pills nav-stacked">
                    <li class="active"><a href="#"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>	Ínicio</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>	Avisos</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>	Agenda Diária</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-list" aria-hidden="true"></span>	Eventos</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>	Configurações</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>	Sair</a></li>		
                </ul>
            </div>
        </aside>

        <div role="main" class="col-md-8">
            <?php echo $this->fetch('content');?>
        </div>

    </div>


    <footer class="row">

    </footer>
</div>

