<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="UTF-8">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> 

<!-- Styles -->
<link href="css/style.css" rel="stylesheet">
<?php
echo $this->Html->script('bootstrap.min') . "\n";
echo $this->Html->script('menu') . "\n";
echo $this->fetch('script');

//echo $this->Html->css('bootstrap.min') . "\n";
echo $this->Html->css('style') . "\n";
echo $this->fetch('css');
?>

<div class="container">
    <header class="row" id="header">
        <h4>Escola ABC123</h4>
    </header>
    <div class="row" id="corpo">
        <aside role="complementary" class="col-md-4" id="menu-lateral">



            <ul class="nav nav-pills nav-stacked">
                <li><a href="home"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>	Ínicio</a></li>
                <li><a href="avisos"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>	Avisos</a></li>
                <li><a href="agenda"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>	Agenda Diária</a></li>
                <li><a href="eventos"><span class="glyphicon glyphicon-list" aria-hidden="true"></span>	Eventos</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>	Configurações <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Séries</a></li>
                        <li><a href="#">Professores</a></li>
                        <li><a href="#">Alunos/Pais</a></li>
                        <li><a href="#">Escola</a></li>
                    </ul>
                </li>
                <li><a href="#"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>	Sair</a></li>		
            </ul>

        </aside>

        <div role="main" class="col-md-8">
            <?php echo $this->fetch('content'); ?>
        </div>
    </div>


    <footer class="row">

    </footer>
</div>

