<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="UTF-8">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> 

<!-- Styles -->
<link href="css/style.css" rel="stylesheet">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<?php
echo $this->Html->script('bootstrap.min') . "\n";
echo $this->Html->script('menu') . "\n";
echo $this->fetch('script');

//echo $this->Html->css('bootstrap.min') . "\n";
echo $this->Html->css('style') . "\n";
echo $this->fetch('css');
?>

<?php $logged = $this->Session->read('loggedStudent') ?>

<div class="container">
    <header class="row" id="header">
        <h4 class="pull-left"><?php echo $logged[0]['schools']['name']; ?></h4>
        <div class="pull-right user-photo-cont" >
            <span>
                <img src="<?php echo $logged[0]['students']['photo']; ?>" class="img-circle student-photo-header" />
            </span>
        </div>
        <div class="pull-right header-name">
            <span>
                <?php echo $logged[0]['students']['name']; ?>
            </span>
            <br/>
            <span>
                Aluno
            </span>
        </div>

    </header>
    <div class="row" id="corpo">
        <aside role="complementary" class="col-md-4" id="menu-lateral">

            <ul class="nav nav-pills nav-stacked">
                <li><a href="home"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>	Ínicio</a></li>
                <li><a href="avisos"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>	Avisos</a></li>
                <li><a href="agenda"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>	Agenda Diária</a></li>
                <li><a href="eventos"><span class="glyphicon glyphicon-list" aria-hidden="true"></span>	Eventos</a></li>
                <li><a href="grade"><span class="glyphicon glyphicon-th" aria-hidden="true"></span>	Grade</a></li>
                <li><a href="configuraUsuario"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>	Configurações</a></li>
                <li><a href="logout"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>	Sair</a></li>		
            </ul>

        </aside>

        <div role="main" class="col-md-8" id="col-md-8">
            <?php echo $this->fetch('content'); ?>
        </div>
    </div>


    <footer class="row">

    </footer>
</div>

