<!-- WEB -->
<?php if (!preg_match("/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i", $_SERVER["HTTP_USER_AGENT"])) { ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> 

    <?php
    echo $this->Html->script('bootstrap.min') . "\n";
    echo $this->Html->script('menu') . "\n";
    echo $this->fetch('script');

//
    echo $this->Html->css('style') . "\n";
    echo $this->fetch('css');
    ?>

    <div class="login-body" style="background: #E6E6FA; height: 100%; position: absolute; width: 100%;">
        
        <div class="form-signin">
            <img src="../img/school/logo/online-school-student.png" />
            <?php if ($loginError) { ?>
                <div class="alert alert-danger" role="alert">Usuário ou Senha inválidos.</div>
            <?php } ?>
            <form class="form" method="post" action="login">
                <input type="email" required autofocus name="email" class="form-control" placeholder="E-mail" /><br/>
                <input type="password" class="form-control" placeholder="Senha" required name="password"/><br/>
                <button class="btn btn-primary" type="submit" id="btnLogin">Entrar</button>
            </form>
        </div>
    </div>
<?php } else { ?>
    <!-- MOBILE -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link rel="shortcut icon" href="img/favicon.ico">
    <link rel="stylesheet" href="../js/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../js/jasny-bootstrap/css/jasny-bootstrap.min.css">
    <link rel="stylesheet" href="../css/page/base.css">
    <script src="../js/jquery/jquery-2.1.4.min.js"></script>
    <script src="../js/bootstrap/js/bootstrap.min.js"></script>
    <script src="../js/jasny-bootstrap/js/jasny-bootstrap.min.js"></script>

    <script src="../js/jquery-storage/jquery.cookie.js"></script>
    <script src="../js/jquery-storage/jquery.storageapi.min.js"></script>
    <script src="../js/jquery-storage/json2.js"></script>

    <link rel="stylesheet" href="../css/page/index.css">

    <div class="container" id="login">
        <div class="row rowLogo">
            <div class="col-xs-12">
                <img src="../img/school/logo/online-school-student.png" class="logologin"/> 
            </div>
        </div>
        <form method="post" action="login">
            <div class="row textLogin marginTop25">
                <div class="col-xs-12 input-box">
                    <input class="form-control transparent-input" autofocus="autofocus" type='text' name='email' placeholder="Email"  required>
                    <div class="bottomLine"></div>
                </div>
            </div>
            <div class="row textLogin marginTop25">
                <div class="col-xs-12 input-box">
                    <input class="form-control transparent-input" type='text' name='password' placeholder="Senha"  required>
                    <div class="bottomLine"></div>
                </div>
            </div>
            <div class="row marginTop25">
                <div class="col-xs-12">
                    <button type="submit" class="btn btn-success btn-lg btn-block" id="enterMobilebuttom">ENTRAR</button>
                </div>
            </div>
        </form>
    </div>
    <script src="../js/page/base.js"></script>
<?php } ?>




