<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> 

<link href="http://code.jonathanbriehl.com/demos/bootstrap-vertical-menu/css/bootstrap.min.css" rel="stylesheet">
<?php
echo $this->Html->css('bootstrap.min');
echo $this->fetch('css');
?>

<style type="text/css">
/*     make sidebar nav vertical  
    @media (min-width: 768px) {
        .sidebar-nav .navbar .navbar-collapse {
            padding: 0;
            max-height: none;
        }
        .sidebar-nav .navbar ul {
            float: none;
        }
        .sidebar-nav .navbar ul:not {
            display: block;

        }
        .sidebar-nav .navbar li {
            float: none;
            display: block;
        }
        .sidebar-nav .navbar li a {
            padding-top: 12px;
            padding-bottom: 12px;
        }
    }
    @media (min-width: 768px) {
         uncomment if you would like the menu to be fixed 
         .navbar {
                position: fixed;
                width: 170px;
                z-index: 2;
        } 
    }
    @media (min-width: 992px) {
        .navbar {
            width: 212px;
        }
    }
    @media (min-width: 1200px) {
        .navbar {
            width: 262px;
        }
    }
    .sidebar-nav .navbar-header{ float: none; }

    .lateral-menu{
        margin: 0px;
        padding: 0px;
        height: 100%;
    }*/

</style>

<div class="container">
    <div class="row" >
        <div class="col-sm-3">
            <div class="sidebar-nav">
                <div class="navbar navbar-default lateral-menu" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <span class="visible-xs navbar-brand">Sidebar menu</span>
                    </div>
                    <div class="navbar-collapse collapse sidebar-navbar-collapse ">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#">Menu Item 1 with a really long name that may or may not wrap</a></li>
                            <li><a href="#">Menu Item 2</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Menu Item 4</a></li>
                            <li><a href="#">Reviews <span class="badge">1,118</span></a></li>
                        </ul>
                    </div>/.nav-collapse 
                </div>
            </div>
        </div>

    </div>

</div>


 Placed at the end of the document so the pages load faster 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="http://code.jonathanbriehl.com/demos/bootstrap-vertical-menu/js/bootstrap.min.js"></script>-->

<?php
echo $this->Html->script('Summernote/summernote.min') . "\n";
echo $this->fetch('script');

$this->Html->css('Summernote/font-awesome/font-awesome.min', array('inline' => false));
$this->Html->css('Summernote/summernote', array('inline' => false));
?>
<?php $this->Html->script('Summernote/summernote.min', array('inline' => false)); ?>
<?php $this->Html->script('Summernote/plugin/summernote-ext-hello', array('inline' => false)); ?>
<?php $this->Html->script('Summernote/plugin/summernote-ext-hint', array('inline' => false)); ?>
<?php $this->Html->script('Summernote/plugin/summernote-ext-video', array('inline' => false)); ?>

<script>

    $(document).ready(function() {
        $('#summernote').summernote();
    });

</script>
<style>
    .summernote{
        color: #000;
    }
</style>
<div id='summernote'></div>