<div id="div-content">
    <div class="cadSeries">
        <form enctype="multipart/form-data" method="post" action="cadastraProfessor">
            <h4>Cadastrar Professor</h4>
            <hr />
            <div>
                <span class="label pull-left">Nome</span>
                <input type="text" class="form-control school-form pull-right" name="name" style="width: 80%;"/>
            </div>
            <br/>
            <br/>
            <hr style="position: relative;"/>

            <div>
                <span class="label pull-left">Email</span>
                <input type="email" class="form-control school-form pull-right" name="email" style="width: 80%;"/>
            </div>
            <br/>
            <br/>
            <hr style="position: relative;"/>

            <div>
                <span class="label pull-left">Telefone</span>
                <input type="phone" class="form-control school-form pull-right" name="phone" style="width: 80%;"/>
            </div>
            <br/>
            <br/>
            <hr style="position: relative;"/>

            <div>
                <span class="label pull-left">Senha</span>
                <input type="password" class="form-control school-form pull-right" name="password" style="width: 80%;"/>
            </div>
            <br/>
            <br/>
            <hr style="position: relative;"/>

            <div>
                <span class="label pull-left">Foto</span>
                <input type="file" class="form-control school-form pull-right" name="photo" style="width: 80%;"/>
            </div>
            <br/>
            <br/>
            <hr style="position: relative;"/>


            <div class="buttons-area">
                <a class="btn btn-primary btn-lg" href="#" role="button"><button type="submit" style="background: transparent; border: 0px;">SALVAR</button></a>
                <a class="btn btn-primary btn-lg" href="#" role="button">CANCELAR</a>
            </div>
        </form>
    </div>
</div>