
<style>
    
    .form-group{
        text-align: left;
        color: #333;
    }
    
</style>
<div id="content">
    <div class="col-md-12">
        <div class="form-group pull-left">
            <label for="name">Nome</label>
            <input type="text" class="form-control"
                                        id="name" name="name">
        </div>

        <div class="form-group pull-left">
            <label for="dataprotocolo">Data de Protocolo</label> <input
                type="date" class="form-control" id="dataprotocolo"
                placeholder="">
        </div>

        <div class="form-group pull-left">
            <label for="datacancelamento">Data de Cancelamento</label> <input
                type="date" class="form-control" id="datacancelamento"
                placeholder="">
        </div>
    </div>
</div>

