<?php
echo $this->Html->script('jquery.min') . "\n";
echo $this->Html->script('bootstrap.min') . "\n";
echo $this->Html->script('base') . "\n";
echo $this->fetch('script');
?>
<?php
echo $this->Html->css('bootstrap.min', null, array('media' => 'screen')) . "\n";
echo $this->fetch('css');
?>

<meta name="apple-itunes-app" content="app-id=502838820">
<meta name="google-play-app" content="app-id=ru.hh.android">

<meta name="msApplication-ID" content="microsoft.build.App"/>
<meta name="msApplication-PackageFamilyName" content="microsoft.build_8wekyb3d8bbwe"/>

<meta name="viewport" content="width=device-width, initial-scale=1.0">


<link rel="stylesheet" type="text/css" href="../css/app-banner/smart-app-banner.css">
<link rel="apple-touch-icon" href="icon.png">
<link rel="android-touch-icon" href="icon.png" />
<link rel="windows-touch-icon" href="icon.png" />

<style type="text/css">
		* {
			box-sizing: border-box;
		}
</style>

<script type="text/javascript" src="../js/app-banner/smart-app-banner.js"></script>

<script>
	banner = undefined;
	function run(force) {
		var n = document.querySelector('.smartbanner');
		if (n) {
			n.parentNode.removeChild(n);
		}
		new SmartBanner({
				daysHidden: 15, // days to hide banner after close button is clicked (defaults to 15)
				daysReminder: 90, // days to hide banner after "VIEW" button is clicked (defaults to 90)
				appStoreLanguage: 'us', // language code for the App Store (defaults to us)
				title: 'KudaGo',
				author: 'KudaGo Inc',
				button: 'OPEN',
				force: force
		});
	};
        
        $(function(){
            
            run('android');
            
        });
</script>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">

                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="brand" href="">Adventa Master</a>

                <!-- Top Menu -->
                <div class="nav-collapse collapse">
                    <?php echo $this->element('top_menu'); ?>
                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class='row'>
            <!-- Sidebar Menu -->
            <div class='span3'>
                <?php echo $this->element('sidebar_menu'); ?>
            </div>

            <div class='span9'>
                <?php echo $this->fetch('content'); ?>
            </div>
        </div>
    </div> <!-- /container -->

</body>